TERMUX_PKG_HOMEPAGE="https://github.com/eclipse-cyclonedds/cyclonedds"
TERMUX_PKG_DESCRIPTION="Eclipse Cyclone DDS is a very performant and robust open-source implementation of the OMG DDS specification"
TERMUX_PKG_LICENSE="EPL-2.0"
TERMUX_PKG_MAINTAINER="Pooya Moradi <pvonmoradi@gmail.com>"
TERMUX_PKG_VERSION="0.10.2"
TERMUX_PKG_SRCURL="https://github.com/eclipse-cyclonedds/cyclonedds/archive/refs/tags/$TERMUX_PKG_VERSION.tar.gz"
TERMUX_PKG_SHA256=bc84e137e0c8a055b8cd97fbeafec94e36de1b0c2e88800896a82384fd867ae5
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="openssl"
# FIXME enable building docs (depends on doxygen)
# FIXME enable DENABLE_SHM
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_EXAMPLES=OFF
-DBUILD_TESTING=OFF
-DBUILD_DOCS=OFF
-DBUILD_IDLC=OFF
-DBUILD_DDSPERF=OFF
-DENABLE_SSL=ON
-DENABLE_SHM=AUTO
-DENABLE_SECURITY=ON
-DENABLE_LIFESPAN=ON
-DENABLE_DEADLINE_MISSED=ON
-DENABLE_TYPE_DISCOVERY=ON
-DENABLE_TOPIC_DISCOVERY=ON
-DENABLE_SOURCE_SPECIFIC_MULTICAST=ON
-DENABLE_IPV6=ON
"
